import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

async function render() {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);
  return worker.fetch(
    new Request("http://localhost/", { headers: { accept: "text/html" } }),
    { ASSETS: { fetch: async () => new Response("Not found", { status: 404 }) } },
    { waitUntil() {}, passThroughOnException() {} },
  );
}

test("server-renders the rebuilt cinematic opening", async () => {
  const response = await render();
  assert.equal(response.status, 200);
  const html = await response.text();
  assert.match(html, /<title>FROM PHOTOGRAPHS TO SPATIAL FIELDS — Gaussian Splatting<\/title>/i);
  assert.match(html, /FROM PHOTOGRAPHS TO SPATIAL FIELDS/);
  assert.match(html, /We are living in a 3D space and a 4D world/);
  assert.doesNotMatch(html, /We live in 3D\.|We remember in 2D\./);
  assert.match(html, /The room in front of you is real geometry/);
  assert.match(html, /LiDAR samples/);
  assert.match(html, /Photogrammetry mesh/);
  assert.match(html, /Gaussian field/);
  assert.match(html, /Live WebGL geometry/);
  assert.match(html, /Same photographs/);
  assert.match(html, /Three representations/);
  assert.match(html, /Photos → mesh → texture/);
  assert.match(html, /Photos → neural network → rendered image/);
  assert.match(html, /Photos → millions of Gaussians → rendered image/);
  assert.match(html, /Space/);
  assert.match(html, /Replay/);
  assert.match(html, /A photograph samples light on a plane/);
  assert.match(html, /A video is a sequence of photographs/);
  assert.match(html, /Interactive Continental Rooftop Gaussian Splatting camera path/);
  assert.doesNotMatch(html, /Official Inria 3D Gaussian Splatting reconstruction of the bicycle scene/);
  assert.match(html, /Real NYC video frame · Caleb Oquendo/);
  assert.match(html, /Opening page 1 of 4/);
  assert.match(html, /Opening page 4 of 4/);
  assert.match(html, /Six decades/);
  assert.match(html, /An image becomes discrete samples/);
  assert.match(html, /A volume sample leaves a footprint/);
  assert.match(html, /Millions of points become interactive/);
  assert.match(html, /Gaussians become the scene/);
  assert.match(html, /Gaussian worlds reach the open web/);
  assert.match(html, /Record first/);
  assert.match(html, /Superman \(2025\)/);
  assert.match(html, /FastGS trained a benchmark scene in about 100 seconds/);
  assert.match(html, /Aerial photographs become an explorable 3DGS environment/);
  assert.match(html, /Pokémon GO players helped turn landmarks into machine-readable 3D maps/);
  assert.match(html, /A captured place becomes a playable level/);
  assert.match(html, /Potential application · inference/);
  assert.match(html, /Page 1 of 12/);
  assert.match(html, /What there for us\?/);
  assert.doesNotMatch(html, /what could it change in our everyday lives|How might we remember/);
  assert.doesNotMatch(html, /Opening step 1 of 4|record-progress|step-dots/);
  assert.match(html, /A recording becomes a place you can move through/);
  assert.match(html, /3D \+ time: space becomes a sequence of states/);
  assert.match(html, /Capture footage and stills · Continental Rooftop/);
  assert.match(html, /Official 4DGS result/);
  assert.doesNotMatch(html, /codex-preview|Your site is taking shape|react-loading-skeleton/i);
});

test("keeps the opening continuous, user-controlled and accessible", async () => {
  const [component, applicationsFinale, endingQuestion, representationPrimer, originsTimeline, recordEvolution, gaussianPrimitive, continentalCameraPath, embeddedCameraPath, linearProgress, spatialKeyboard, css] = await Promise.all([
    readFile(new URL("../app/OpeningExperience.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/ApplicationsFinale.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/EndingQuestion.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RepresentationPrimer.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/OriginsTimeline.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/RecordEvolution.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/GaussianPrimitiveWebGL.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/ContinentalCameraPathHero.tsx", import.meta.url), "utf8"),
    readFile(new URL("../public/media/continental-camera-path/index.html", import.meta.url), "utf8"),
    readFile(new URL("../app/LinearProgress.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/spatialKeyboard.ts", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(component, /new THREE\.WebGLRenderer/);
  assert.match(component, /RoundedBoxGeometry/);
  assert.match(component, /real-three-dimensional-room/);
  assert.match(component, /new THREE\.WebGLRenderTarget/);
  assert.match(component, /buildRepresentations/);
  assert.match(component, /THREE\.Points/);
  assert.match(component, /THREE\.WireframeGeometry/);
  assert.match(component, /THREE\.InstancedBufferGeometry/);
  assert.match(component, /THREE\.ShaderMaterial/);
  assert.match(component, /anisotropic-gaussian-field/);
  assert.match(component, /Gaussian<br \/>Splatting/);
  assert.match(component, /Not a flat image\. A field you can enter and explore\./);
  assert.match(component, /spatialKeyDirection/);
  assert.match(component, /sectionOwnsViewportCenter/);
  assert.match(component, /keyboardTargetIsInteractive/);
  assert.match(component, /continueToStory/);
  assert.match(component, /ContinentalCameraPathHero/);
  assert.doesNotMatch(component, /GaussianFieldHero|WorldLabsSplatViewer|WorldLabsVideoHero/);
  assert.match(component, /openingIds/);
  assert.match(component, /openingPanelRefs/);
  assert.match(component, /opening-sequence/);
  assert.doesNotMatch(component, /step-dots|Opening step/);
  assert.match(linearProgress, /opening-space/);
  assert.match(linearProgress, /opening-gaussian/);
  assert.match(linearProgress, /"representations"/);
  assert.match(linearProgress, /"timeline"/);
  assert.match(linearProgress, /"4dgs"/);
  assert.match(linearProgress, /"ending"/);
  assert.match(linearProgress, /linear-page-number/);
  assert.match(linearProgress, /padStart\(2, "0"\)/);
  assert.match(linearProgress, /goToPage/);
  assert.match(linearProgress, /window\.scrollTo/);
  assert.match(linearProgress, /window\.scrollY \+ target\.getBoundingClientRect\(\)\.top/);
  assert.match(linearProgress, /history\.replaceState/);
  assert.match(linearProgress, /spatial:navigate/);
  assert.match(linearProgress, /aria-current/);
  assert.match(css, /\.linear-progress button \{/);
  assert.ok(linearProgress.indexOf('"4dgs"') < linearProgress.indexOf('"timeline"'));
  assert.ok(linearProgress.indexOf('"opening-gaussian"') < linearProgress.indexOf('"representations"'));
  assert.ok(linearProgress.indexOf('"representations"') < linearProgress.indexOf('"story"'));
  assert.ok(linearProgress.indexOf('"timeline"') < linearProgress.indexOf('"applications"'));
  assert.ok(linearProgress.indexOf('"applications"') < linearProgress.indexOf('"ending"'));
  assert.match(continentalCameraPath, /continental-camera-path\/index\.html\?embed=1&autoplay=0/);
  assert.match(continentalCameraPath, /postMessage/);
  assert.match(continentalCameraPath, /Drag to orbit · Scroll to zoom/);
  assert.match(embeddedCameraPath, /setPlaying\(playbackRequested\)/);
  assert.match(embeddedCameraPath, /action: 'ready'/);
  assert.match(embeddedCameraPath, /action: 'navigate', direction/);
  assert.match(embeddedCameraPath, /event\.key === 'Enter'/);
  assert.match(embeddedCameraPath, /event\.key === 'ArrowDown'/);
  assert.match(embeddedCameraPath, /event\.key === 'ArrowUp'/);
  assert.match(continentalCameraPath, /event\.data\.direction === 1 \|\| event\.data\.direction === -1/);
  assert.match(spatialKeyboard, /event\.key === "ArrowUp"/);
  assert.match(spatialKeyboard, /event\.key === "Enter"/);
  assert.match(spatialKeyboard, /event\.key === "ArrowDown"/);
  assert.match(spatialKeyboard, /event\.code === "Space"/);
  assert.match(spatialKeyboard, /sectionOwnsViewportCenter/);
  for (const keyboardComponent of [component, applicationsFinale, endingQuestion, representationPrimer, originsTimeline, recordEvolution]) {
    assert.match(keyboardComponent, /spatialKeyDirection/);
    assert.match(keyboardComponent, /stopImmediatePropagation/);
  }
  assert.match(component, /addEventListener\("wheel", onWheel, \{ passive: false \}\)/);
  assert.match(component, /nextDirection === 1 \? currentStep < 3 : currentStep > 0/);
  assert.match(component, /wheelGestureLocked/);
  assert.match(component, /wheelReleaseTimer/);
  assert.match(component, /}, 280\)/);
  assert.match(component, /applyCanonicalOpeningStep\(1\);\s*await scrollToOpeningStep\(targetStep, true\);\s*currentStep = targetStep;\s*setStep\(targetStep\);\s*setMotion\("unfold"\);\s*await unfoldRoom\(\);/);
  assert.equal(component.match(/await unfoldRoom\(\)/g)?.length, 1);
  assert.match(component, /targetStep === 1[\s\S]*room\.visible = false;[\s\S]*photoPlane\.visible = true;[\s\S]*photoMaterial\.opacity = 1;[\s\S]*setMaterialOpacity\(solidMaterials, 0\);[\s\S]*setGaussianOpacity\(0\);[\s\S]*lookFrom\(frontCamera\);/);
  assert.match(component, /sourceStep === 2 \? "fold"/);
  assert.match(component, /unflattenRoom/);
  assert.match(component, /foldRoom/);
  assert.match(component, /rewindRepresentations/);
  assert.match(component, /setRun/);
  assert.match(component, /await animate\(3000/);
  assert.match(component, /await animate\(4000/);
  assert.match(originsTimeline, /1965/);
  assert.match(originsTimeline, /1989/);
  assert.match(originsTimeline, /2000/);
  assert.match(originsTimeline, /2023/);
  assert.match(originsTimeline, /2025/);
  assert.match(originsTimeline, /timeline\.play\(\)/);
  assert.match(originsTimeline, /Autoplay on arrival/);
  assert.match(originsTimeline, /timeline\.timeScale\(0\.82\)/);
  assert.match(originsTimeline, /focusedMilestone/);
  assert.match(originsTimeline, /has-hover-focus/);
  assert.match(originsTimeline, /hoverIntentRef/);
  assert.match(originsTimeline, /hoverExitRef/);
  assert.match(originsTimeline, /onPointerEnter=\{\(\) => requestMilestoneFocus\(index\)\}/);
  assert.match(originsTimeline, /onPointerLeave=\{releaseMilestoneFocus\}/);
  assert.match(originsTimeline, /}, 85\)/);
  assert.match(originsTimeline, /}, 140\)/);
  assert.doesNotMatch(originsTimeline, /clipPath/);
  assert.doesNotMatch(originsTimeline, /"\.qsplat-bust i"/);
  assert.match(originsTimeline, /tabIndex=\{0\}/);
  assert.doesNotMatch(originsTimeline, /document\.getElementById\("story"\)/);
  assert.match(originsTimeline, /document\.getElementById\("applications"\)/);
  assert.match(originsTimeline, /worldlabs-coit-tower\.mp4/);
  assert.match(originsTimeline, /function stableNumber/);
  assert.match(originsTimeline, /"--point-opacity": `\$\{point\.opacity\}`/);
  assert.match(originsTimeline, /mariner4-hand-colored\.jpg/);
  assert.match(originsTimeline, /inria-bicycle-3dgs\.jpg/);
  assert.match(originsTimeline, /addEventListener\("wheel", onWheel, \{ passive: false \}\)/);
  assert.doesNotMatch(originsTimeline, /World Labs.*first|first.*World Labs/i);
  assert.match(css, /@keyframes phoneScan/);
  assert.match(css, /\.history-timeline/);
  assert.match(css, /--timeline-grid-top:\s*32%/);
  assert.match(css, /top:\s*var\(--timeline-grid-top\)/);
  assert.match(css, /\.timeline-grid\.has-hover-focus \.timeline-milestone:not\(\.is-hovered\)/);
  assert.match(css, /\.timeline-grid\.has-hover-focus \.timeline-milestone\.is-hovered/);
  assert.match(css, /\.application-copy \{[^}]*padding: 16px 4px 0/);
  assert.match(css, /\.applications-grid \{[^}]*grid-template-rows: repeat\(2,minmax\(0,1fr\)\)/);
  assert.doesNotMatch(applicationsFinale, /application-progress/);
  assert.doesNotMatch(css, /\.application-progress/);
  assert.match(css, /\.cinema-visual \{[^}]*grid-template-columns: repeat\(2,minmax\(0,1fr\)\)/);
  assert.doesNotMatch(css, /\.cinema-visual \{[^}]*grid-template-rows: repeat\(2,minmax\(0,1fr\)\)/);
  assert.match(css, /\.cinema-stage img \{[^}]*object-fit: cover/);
  assert.doesNotMatch(css, /\.cinema-stage img \{[^}]*transform: scale/);
  assert.match(css, /\.cinema-stage-final img \{ object-position: center 15%; \}/);
  assert.match(css, /prefers-reduced-motion:\s*reduce/);
  assert.doesNotMatch(css, /scroll-snap|rotateX\(5\.5deg\)/);
  assert.match(recordEvolution, /import gsap from "gsap"/);
  assert.match(recordEvolution, /timeline\.reverse\(\)/);
  assert.match(recordEvolution, /document\.getElementById\("timeline"\)/);
  assert.match(recordEvolution, /boundarySection\?\.scrollIntoView/);
  assert.match(recordEvolution, /addEventListener\("wheel", onWheel, \{ passive: false \}\)/);
  assert.match(recordEvolution, /nyc-window\.mp4/);
  assert.match(recordEvolution, /continental-rooftop-capture-loop\.mp4/);
  assert.match(recordEvolution, /continental-rooftop-capture-poster\.jpg/);
  assert.match(recordEvolution, /continental-rooftop-view-01\.jpg/);
  assert.match(recordEvolution, /continental-rooftop-view-02\.jpg/);
  assert.match(recordEvolution, /continental-rooftop-view-03\.jpg/);
  assert.match(recordEvolution, /Capture 01/);
  assert.doesNotMatch(recordEvolution, /s07-3dgs-playroom-left/);
  assert.doesNotMatch(recordEvolution, /s07-3dgs-playroom-front/);
  assert.doesNotMatch(recordEvolution, /s07-3dgs-playroom-right/);
  assert.doesNotMatch(recordEvolution, /<source src=\{`\$\{mediaRoot\}\/inria-3dgs-playroom\.mp4`\}/);
  assert.match(recordEvolution, /\[1, 2, 3, 4, 5, 6, 7\]/);
  assert.match(recordEvolution, /className="video-frame"/);
  assert.doesNotMatch(recordEvolution, /frames \/ second/);
  assert.doesNotMatch(recordEvolution, /className="time-axis"/);
  assert.doesNotMatch(recordEvolution, /className="frame-counter"/);
  assert.match(recordEvolution, /const depthStep/);
  assert.match(recordEvolution, /z: \(itemIndex\) => \(itemIndex - 3\) \* depthStep/);
  assert.match(css, /\.video-frame-camera \{[^}]*perspective: 4000px/);
  assert.match(css, /perspective-origin: 50% 18%/);
  assert.match(css, /\.video-frame-world \{[^}]*rotateX\(26deg\) rotateY\(58deg\)/);
  assert.match(css, /\.video-frame \{[^}]*transform-style: preserve-3d/);
  assert.match(recordEvolution, /rotationX: 0/);
  assert.match(recordEvolution, /rotationY: 0/);
  assert.match(recordEvolution, /rotationZ: 0/);
  assert.doesNotMatch(css, /\.video-frame \{[^}]*rotate[XYZ]\(/);
  assert.doesNotMatch(recordEvolution, /stereo-pair|anaglyph-result|stereo-verdict/);
  assert.doesNotMatch(recordEvolution, /record-progress/);
  assert.match(recordEvolution, /s09-interstellar-tesseract/);
  assert.match(css, /\.record-chapter/);
  assert.match(css, /\.linear-progress/);
  assert.match(css, /\.gaussian-primitive-demo/);
  assert.match(recordEvolution, /GaussianPrimitiveWebGL/);
  assert.match(gaussianPrimitive, /new THREE\.WebGLRenderer/);
  assert.match(gaussianPrimitive, /new THREE\.ShaderMaterial/);
  assert.match(gaussianPrimitive, /new THREE\.Timer/);
  assert.doesNotMatch(gaussianPrimitive, /new THREE\.Clock/);
  assert.match(gaussianPrimitive, /exp\(-3\.2 \* dot\(samplePosition, samplePosition\)\)/);
  assert.match(gaussianPrimitive, /volume\.scale\.set\(2\.32, 0\.92, 1\.3\)/);
  assert.doesNotMatch(css, /\.primitive-core/);
  assert.match(css, /\.applications-finale/);
  assert.match(css, /\.representation-primer/);
  assert.match(css, /\.primer-methods/);
  assert.match(css, /\.primer-splat-field i/);
  assert.match(representationPrimer, /function MeshDiagram/);
  assert.match(representationPrimer, /<canvas ref=\{canvasRef\}/);
  assert.match(representationPrimer, /paintFace/);
  assert.match(representationPrimer, /Vertices/);
  assert.match(representationPrimer, /Edges/);
  assert.match(representationPrimer, /Faces/);
  assert.match(representationPrimer, /gaussian-rendered-image\.png/);
  assert.match(representationPrimer, /type === "gaussian"/);
  assert.doesNotMatch(representationPrimer, /stanford-bunny-triangular-mesh/);
  assert.doesNotMatch(representationPrimer, /primer-mesh-lines/);
  assert.match(css, /\.primer-mesh-specimen canvas \{[^}]*width: 100%/);
  assert.match(css, /\.primer-result-gaussian img \{[^}]*object-fit: contain;[^}]*filter: none;/);
  assert.doesNotMatch(css, /\.primer-mesh-lines/);
  assert.match(css, /--type-large:\s*clamp\(52px, 5vw, 88px\)/);
  assert.match(css, /--type-medium:\s*clamp\(18px, 1\.35vw, 26px\)/);
  assert.match(css, /--type-small:\s*clamp\(12px, \.78vw, 15px\)/);
  assert.match(css, /\.opening-page \* \{ font-size: var\(--type-small\) !important; \}/);
  assert.match(css, /@media \(max-width: 1180px\)/);
  assert.match(css, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
  assert.match(applicationsFinale, /Autoplay on arrival/);
  assert.match(applicationsFinale, /timeline\.timeScale\(0\.82\)/);
  assert.match(applicationsFinale, /apple-maps-enhanced-flyover\.jpg/);
  assert.match(applicationsFinale, /fastgs-counter/);
  assert.match(applicationsFinale, /cinema-stage-capture/);
  assert.match(applicationsFinale, /cinema-stage-final/);
  assert.match(applicationsFinale, /superman-4dgs-capture-context\.jpg/);
  assert.match(applicationsFinale, /superman-4dgs-final-context\.jpg/);
  assert.match(applicationsFinale, /192-camera stage/);
  assert.match(applicationsFinale, /Fortress hologram/);
  assert.match(applicationsFinale, /Aerial 3DGS reconstruction/);
  assert.match(applicationsFinale, /Aerial photographs become an explorable 3DGS environment/);
  assert.match(applicationsFinale, /VastGaussian/);
  assert.match(applicationsFinale, /Aerial images/);
  assert.match(applicationsFinale, /SfM \+ sparse points/);
  assert.match(applicationsFinale, /Parallel cells/);
  assert.match(applicationsFinale, /Merged 3DGS/);
  assert.doesNotMatch(applicationsFinale, /Robotics|SplaTAM|robotics-/);
  assert.match(applicationsFinale, /Crowdsourced spatial mapping/);
  assert.match(applicationsFinale, /optional PokéStop Scan tasks/);
  assert.match(applicationsFinale, /Lightship VPS/);
  assert.match(applicationsFinale, /Playable environments/);
  assert.match(applicationsFinale, /Postcard combines Gaussian splats/);
  assert.match(applicationsFinale, /vastgaussian-mill19-building\.mp4/);
  assert.match(applicationsFinale, /pokemon-go-reality-blending\.png/);
  assert.doesNotMatch(applicationsFinale, /niantic-vps-workflow\.jpg/);
  assert.doesNotMatch(applicationsFinale, /Creative tools|painting-with-splats/);
  assert.match(applicationsFinale, /postcard-gaussian-game\.jpg/);
  assert.doesNotMatch(applicationsFinale, /Cultural heritage|gaussian-heritage/);
  assert.match(applicationsFinale, /document\.getElementById\("ending"\)/);
  assert.doesNotMatch(applicationsFinale, /cinema-camera-frame/);
  assert.match(applicationsFinale, /timeline\.reverse\(\)/);
  assert.match(applicationsFinale, /addEventListener\("wheel", onWheel, \{ passive: false \}\)/);
  assert.match(recordEvolution, /Playing automatically/);
  assert.match(recordEvolution, /timeline\.timeScale\(0\.82\)/);
  assert.match(recordEvolution, /nyc-window-pixel-detail-48\.png/);
  assert.match(recordEvolution, /48 by 48 pixel crop enlarged with nearest-neighbor rendering/);
  assert.match(css, /\.pixel-sample-image img \{[^}]*image-rendering: pixelated;/);
  assert.match(css, /\.pixel-sample-image::after \{[^}]*background-size: 2\.083333% 2\.083333%;/);
  assert.match(component, /duration \* 1\.18/);
  assert.match(component, /addEventListener\("spatial:navigate", onProgressNavigate\)/);
  assert.match(component, /targetStep \* window\.innerHeight/);
  await access(new URL("../app/OpeningExperience.tsx", import.meta.url));
  assert.match(component, /<RecordEvolution key="record-evolution-2-5d" \/>/);
  assert.match(component, /<RepresentationPrimer \/>/);
  assert.match(component, /<EndingQuestion \/>/);
  assert.ok(component.indexOf("<RepresentationPrimer />") < component.indexOf("<RecordEvolution"));
  assert.ok(component.indexOf("<RecordEvolution") < component.indexOf("<OriginsTimeline />"));
  assert.ok(component.indexOf("<OriginsTimeline />") < component.indexOf("<ApplicationsFinale />"));
  assert.ok(component.indexOf("<ApplicationsFinale />") < component.indexOf("<EndingQuestion />"));
  assert.match(endingQuestion, /What there for us\?/);
  assert.match(endingQuestion, /new IntersectionObserver/);
  assert.match(endingQuestion, /data-active=\{active\}/);
  assert.doesNotMatch(endingQuestion, /<b\s*\/>/);
  assert.match(css, /endingGlowSweep/);
  assert.match(css, /endingFieldDrift/);
  assert.doesNotMatch(endingQuestion, /As Gaussian Splatting turns ordinary places into explorable worlds|what could it change in our everyday lives|How might we remember/);
  assert.match(endingQuestion, /Return to the beginning/);
  assert.match(representationPrimer, /Photogrammetry/);
  assert.match(representationPrimer, /NeRF/);
  assert.match(representationPrimer, /Gaussian Splatting/);
  assert.match(representationPrimer, /Photos → mesh → texture/);
  assert.match(representationPrimer, /Photos → neural network → rendered image/);
  assert.match(representationPrimer, /Photos → millions of Gaussians → rendered image/);
  assert.match(representationPrimer, /<h3><i>\{method\.index\}<\/i>\{method\.name\}<\/h3>/);
  assert.match(representationPrimer, /<p><b>\{method\.title\}<\/b> \{method\.detail\}<\/p>/);
  assert.match(representationPrimer, /timeline\.timeScale\(0\.78\)/);
  assert.match(representationPrimer, /const stepLabels = \["step-01", "step-02", "step-03"\]/);
  assert.match(representationPrimer, /timeline\.tweenTo\(stepLabels\[targetStep\]/);
  assert.match(representationPrimer, /returnToOpening/);
  assert.match(representationPrimer, /01 plays on arrival/);
  assert.doesNotMatch(representationPrimer, /timeline\.play\(\)/);
  assert.match(representationPrimer, /document\.getElementById\("story"\)/);
  assert.match(representationPrimer, /addEventListener\("wheel", onWheel, \{ passive: false \}\)/);
  assert.match(css, /\.primer-method-copy h3 \{ font-size: clamp\(28px,2\.2vw,42px\) !important; \}/);
  assert.match(css, /\.primer-method-copy h3 i \{ margin-right: \.52em;/);
  assert.match(css, /\.primer-method-copy p \{ font-size: clamp\(14px,\.9vw,17px\) !important; \}/);
  assert.doesNotMatch(css, /\.primer-method-copy > span/);
  await access(new URL("../public/media/timeline/mariner4-hand-colored.jpg", import.meta.url));
  await access(new URL("../public/media/timeline/inria-bicycle-3dgs.jpg", import.meta.url));
  await access(new URL("../public/media/timeline/worldlabs-coit-tower.mp4", import.meta.url));
  await access(new URL("../public/media/applications/apple-maps-enhanced-flyover.jpg", import.meta.url));
  await access(new URL("../public/media/applications/superman-4dgs-capture.jpg", import.meta.url));
  await access(new URL("../public/media/applications/superman-4dgs-final.jpg", import.meta.url));
  await access(new URL("../public/media/applications/superman-4dgs-final-wide.jpg", import.meta.url));
  await access(new URL("../public/media/applications/superman-4dgs-capture-context.jpg", import.meta.url));
  await access(new URL("../public/media/applications/superman-4dgs-final-context.jpg", import.meta.url));
  await access(new URL("../public/media/applications/fastgs-train.mp4", import.meta.url));
  await access(new URL("../public/media/applications/vastgaussian-mill19-building.mp4", import.meta.url));
  await access(new URL("../public/media/applications/vastgaussian-mill19-building-poster.png", import.meta.url));
  await access(new URL("../public/media/applications/pokemon-go-reality-blending.png", import.meta.url));
  await access(new URL("../public/media/applications/postcard-gaussian-game.jpg", import.meta.url));
  await access(new URL("../public/media/world-labs/ancient-stone-crypt-official.mp4", import.meta.url));
  await access(new URL("../public/media/world-labs/ancient-stone-crypt-thumbnail.webp", import.meta.url));
  await access(new URL("../public/media/continuity/nyc-window.mp4", import.meta.url));
  await access(new URL("../public/media/continuity/nyc-window-photo-1920.webp", import.meta.url));
  await access(new URL("../public/media/continuity/nyc-window-pixel-detail-48.png", import.meta.url));
  await access(new URL("../public/media/record-evolution/inria-3dgs-playroom.mp4", import.meta.url));
  await access(new URL("../public/media/record-evolution/continental-rooftop-capture-loop.mp4", import.meta.url));
  await access(new URL("../public/media/record-evolution/continental-rooftop-capture-poster.jpg", import.meta.url));
  await access(new URL("../public/media/record-evolution/continental-rooftop-view-01.jpg", import.meta.url));
  await access(new URL("../public/media/record-evolution/continental-rooftop-view-02.jpg", import.meta.url));
  await access(new URL("../public/media/record-evolution/continental-rooftop-view-03.jpg", import.meta.url));
  await access(new URL("../public/media/record-evolution/cvpr2024-4dgs-standup-time.mp4", import.meta.url));
  await access(new URL("../public/media/representation-primer/gaussian-rendered-image.png", import.meta.url));
  await access(new URL("../public/media/continental-camera-path/assets/scene.ply", import.meta.url));
  await access(new URL("../public/media/continental-camera-path/assets/transforms.json", import.meta.url));
});
